spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/futureKorea?serverTimezone=Asia/Seoul
    username: root
    password: 1234

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
h2:
  console:
    enabled: true
    path: /h2-console

jwt:
  secret-key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest

oauth:
  kakao:
    client-id: ff3fbec59eb79359987b60913bbff785
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
